{
 "title": "New dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "liters", "label": "liters", "query": "100" }
  ]
 },
 "panels": [
  { "title": "Laptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last Laptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n    (\n        selector_last(\"LapLastLapTime\", \"time\")['value']\n    ) AS \"LapLastLapTime\"\nFROM\n    \"telemetry_data\"\nWHERE\n    $__timeFilter(\"time\") AND \"LapLastLapTime\" IS NOT NULL\nAND lap > 0 AND \"IsInGarage\" is False AND \"OnPitRoad\" is False;\n"
    }
   ]
  },
  {
   "title": "Average Laptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT lap,\n  AVG(\"LapLastLapTime\")\nFROM\n  \"telemetry_data\"\nWHERE\n  $__timeFilter(\"time\")\n  AND \"LapLastLapTime\" IS NOT NULL AND \"LapLastLapTime\" > 0\n  AND \"lap\" > 0\n  AND \"IsInGarage\" is False\n  AND \"OnPitRoad\" is False\nGROUP BY\n  \"lap\""
    }
   ]
  },
  {
   "title": "Fastest Laptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT MIN(\"LapLastLapTime\")\nFROM\n    \"telemetry_data\"\nWHERE\n    $__timeFilter(\"time\") AND \"LapLastLapTime\" IS NOT NULL AND \"LapLastLapTime\" > 0\nAND lap > 0 AND \"IsInGarage\" is False AND \"OnPitRoad\" is False\nGROUP BY \"lap\";\n"
    }
   ]
  },
  {
   "title": "Laps remaining",
   "type": "stat",
   "description": "number of lapremaining based on average laptime",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n    (\n        selector_first(\"SessionTimeRemain\", \"time\")['value'] / mean(\"LapLastLapTime\")\n    ) - CAST(selector_last(\"lap\", \"time\")['value'] AS INT)\n    AS \"laps_remaining\"\nFROM\n    \"telemetry_data\"\nWHERE\n    $__timeFilter(\"time\");"
    }
   ]
  },
  { "title": "Critical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Fuel Remaining",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n    (\n        selector_last(\"FuelLevelPct\", \"time\")['value']\n    ) AS \"FuelLevelPct\"\nFROM\n    \"telemetry_data\"\nWHERE\n    $__timeFilter(\"time\") AND \"FuelLevelPct\" IS NOT NULL;\n"
    }
   ]
  },
  {
   "title": "Time Remaining",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n    (\n        selector_last(\"SessionTimeRemain\", \"time\")['value']\n    ) AS \"last_minutes_remaining\"\nFROM\n    \"telemetry_data\"\nWHERE\n    $__timeFilter(\"time\") AND \"SessionTimeRemain\" IS NOT NULL;\n"
    }
   ]
  },
  {
   "title": "Fuel to finish",
   "type": "stat",
   "description": "number of lapremaining based on average laptime",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "WITH fuel_usage AS (\n    SELECT\n        lap,\n        CASE\n            WHEN selector_first(\"FuelLevel\", \"time\")['value'] - selector_last(\"FuelLevel\", \"time\")['value'] < 0 THEN 0\n            ELSE selector_first(\"FuelLevel\", \"time\")['value'] - selector_last(\"FuelLevel\", \"time\")['value']\n        END AS fuel_per_lap\n    FROM\n        \"telemetry_data\"\n    WHERE\n        time >= $__timeFrom() AND time <= $__timeTo()\n        AND \"lap\" > 0\n    GROUP BY\n        lap\n)\nSELECT\n    GREATEST(0, (selector_first(\"SessionTimeRemain\", \"time\")['value'] / mean(\"LapLastLapTime\"))) * mean(fuel_usage.fuel_per_lap) AS \"fuel_needed\"\nFROM\n    \"telemetry_data\",\n    fuel_usage\nWHERE\n    time >= $__timeFrom() AND time <= $__timeTo()"
    }
   ]
  },
  {
   "title": "Pitstops remaining",
   "type": "stat",
   "description": "number of pitstop remaining",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "WITH fuel_usage AS (\n    SELECT\n        lap,\n        CASE\n            WHEN selector_first(\"FuelLevel\", \"time\")['value'] - selector_last(\"FuelLevel\", \"time\")['value'] < 0 THEN 0\n            ELSE selector_first(\"FuelLevel\", \"time\")['value'] - selector_last(\"FuelLevel\", \"time\")['value']\n        END AS fuel_per_lap\n    FROM\n        \"telemetry_data\"\n    WHERE\n        time >= $__timeFrom() AND time <= $__timeTo()\n        AND \"lap\" > 0\n    GROUP BY\n        lap\n),\nfuel_needed AS (\n    SELECT\n        GREATEST(0, (selector_first(\"SessionTimeRemain\", \"time\")['value'] / mean(\"LapLastLapTime\"))) * mean(fuel_usage.fuel_per_lap) AS total_fuel_needed\n    FROM\n        \"telemetry_data\",\n        fuel_usage\n    WHERE\n        time >= $__timeFrom() AND time <= $__timeTo()\n)\nSELECT\n    ceil(total_fuel_needed / $liters) AS \"pitstops_remaining\"\nFROM\n    fuel_needed"
    }
   ]
  },
  { "title": "Tyres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "LF",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n    (\n        selector_last(\"LFtempCM\", \"time\")['value']\n    ) AS \"LFtempCM\"\nFROM\n    \"telemetry_data\"\nWHERE\n    $__timeFilter(\"time\") AND \"LFtempCM\" IS NOT NULL;\n"
    }
   ]
  },
  {
   "title": "RF",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n    (\n        selector_last(\"RFtempCM\", \"time\")['value']\n    ) AS \"RFtempCM\"\nFROM\n    \"telemetry_data\"\nWHERE\n    $__timeFilter(\"time\") AND \"RFtempCM\" IS NOT NULL;\n"
    }
   ]
  },
  {
   "title": "LR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n    (\n        selector_last(\"LRtempCM\", \"time\")['value']\n    ) AS \"LRtempCM\"\nFROM\n    \"telemetry_data\"\nWHERE\n    $__timeFilter(\"time\") AND \"LRtempCM\" IS NOT NULL;\n"
    }
   ]
  },
  {
   "title": "RR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n    (\n        selector_last(\"RRtempCM\", \"time\")['value']\n    ) AS \"RRtempCM\"\nFROM\n    \"telemetry_data\"\nWHERE\n    $__timeFilter(\"time\") AND \"RRtempCM\" IS NOT NULL;\n"
    }
   ]
  },
  { "title": "Session", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Current driver",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT distinct(driver) FROM \"telemetry_data\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Time Remaining",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n    (\n        selector_last(\"SessionTimeRemain\", \"time\")['value']\n    ) AS \"last_minutes_remaining\"\nFROM\n    \"telemetry_data\"\nWHERE\n    $__timeFilter(\"time\") AND \"SessionTimeRemain\" IS NOT NULL;\n"
    }
   ]
  },
  {
   "title": "On Track",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 16 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT selector_first(\"IsOnTrack\", \"time\")['value']  FROM \"telemetry_data\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo \n"
    }
   ]
  },
  {
   "title": "Current track",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 16 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT distinct(track) FROM \"telemetry_data\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  { "title": "Fuel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Fuel Remaining",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n    (\n        selector_last(\"FuelLevelPct\", \"time\")['value']\n    ) AS \"FuelLevelPct\"\nFROM\n    \"telemetry_data\"\nWHERE\n    $__timeFilter(\"time\") AND \"FuelLevelPct\" IS NOT NULL;\n"
    }
   ]
  },
  {
   "title": "Fuel Average",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 3, "y": 20 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "WITH FuelUsagePerLap AS (\n    SELECT\n        \"lap\",\n        CASE\n            WHEN selector_first(\"FuelLevel\", \"time\")['value'] - selector_last(\"FuelLevel\", \"time\")['value'] < 0 THEN 0\n            ELSE selector_first(\"FuelLevel\", \"time\")['value'] - selector_last(\"FuelLevel\", \"time\")['value']\n        END AS \"FuelPerLap\"\n    FROM\n        \"telemetry_data\"\n    WHERE\n        $__timeFilter(\"time\") AND \"lap\" > 0\n    GROUP BY\n        \"lap\"\n)\nSELECT\n    AVG(\"FuelPerLap\") AS \"Avg\",\n    MIN(CASE WHEN \"FuelPerLap\" > 0 THEN \"FuelPerLap\" ELSE NULL END) AS \"Min\",\n    MAX(\"FuelPerLap\") AS \"Max\"\nFROM\n    FuelUsagePerLap;"
    }
   ]
  },
  {
   "title": "Fuel usage per  last 5 laps",
   "type": "table",
   "description": "Fuel usage per lap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n    lap,\n    CASE\n        WHEN fuel_change < 0 THEN 0\n        ELSE fuel_change\n    END AS fuel_per_lap\nFROM\n    (\n        SELECT\n            lap,\n            selector_first(\"FuelLevel\", \"time\")['value'] - selector_last(\"FuelLevel\", \"time\")['value'] AS fuel_change\n        FROM\n            \"telemetry_data\"\n        WHERE\n            time >= $__timeFrom() AND time <= $__timeTo()\n            AND lap > 0\n        GROUP BY\n            lap\n    )\nORDER BY lap DESC\nLIMIT 5"
    }
   ]
  }
 ]
}