iracing_telemetry_data = {
    "AirDensity": {"description": "Density of air at start/finish line", "unit": "kg/m^3"},
    "AirPressure": {"description": "Pressure of air at start/finish line", "unit": "Pa"},
    "AirTemp": {"description": "Temperature of air at start/finish line", "unit": "C"},
    "Brake": {"description": "0=brake released to 1=max pedal force", "unit": "%"},
    "BrakeABSactive": {"description": "true if abs is currently reducing brake force pressure", "unit": ""},
    "BrakeRaw": {"description": "Raw brake input 0=brake released to 1=max pedal force", "unit": "%"},
    "CamCameraNumber": {"description": "Active camera number", "unit": ""},
    "CamCameraState": {"description": "State of camera system", "unit": "irsdk_CameraState"},
    "CamCarIdx": {"description": "Active camera's focus car index", "unit": ""},
    "CamGroupNumber": {"description": "Active camera group number", "unit": ""},
    "CarDistAhead": {"description": "Distance to first car in front of player in meters", "unit": "m"},
    "CarDistBehind": {"description": "Distance to first car behind player in meters", "unit": "m"},
    "CarIdxBestLapNum": {"description": "Cars best lap number", "unit": ""},
    "CarIdxBestLapTime": {"description": "Cars best lap time", "unit": "s"},
    "CarIdxClass": {"description": "Cars class id by car index", "unit": ""},
    "CarIdxClassPosition": {"description": "Cars class position in race by car index", "unit": ""},
    "CarIdxEstTime": {"description": "Estimated time to reach current location on track", "unit": "s"},
    "CarIdxF2Time": {"description": "Race time behind leader or fastest lap time otherwise", "unit": "s"},
    "CarIdxFastRepairsUsed": {"description": "How many fast repairs each car has used", "unit": ""},
    "CarIdxGear": {"description": "-1=reverse 0=neutral 1..n=current gear by car index", "unit": ""},
    "CarIdxLap": {"description": "Laps started by car index", "unit": ""},
    "CarIdxLapCompleted": {"description": "Laps completed by car index", "unit": ""},
    "CarIdxLapDistPct": {"description": "Percentage distance around lap by car index", "unit": "%"},
    "CarIdxLastLapTime": {"description": "Cars last lap time", "unit": "s"},
    "CarIdxOnPitRoad": {"description": "On pit road between the cones by car index", "unit": ""},
    "CarIdxP2P_Count": {"description": "Push2Pass count of usage (or remaining in Race)", "unit": ""},
    "CarIdxP2P_Status": {"description": "Push2Pass active or not", "unit": ""},
    "CarIdxPaceFlags": {"description": "Pacing status flags for each car", "unit": "irsdk_PaceFlags"},
    "CarIdxPaceLine": {"description": "What line cars are pacing in or -1 if not pacing", "unit": ""},
    "CarIdxPaceRow": {"description": "What row cars are pacing in or -1 if not pacing", "unit": ""},
    "CarIdxPosition": {"description": "Cars position in race by car index", "unit": ""},
    "CarIdxQualTireCompound": {"description": "Cars Qual tire compound", "unit": ""},
    "CarIdxQualTireCompoundLocked": {"description": "Cars Qual tire compound is locked-in", "unit": ""},
    "CarIdxRPM": {"description": "Engine rpm by car index", "unit": "revs/min"},
    "CarIdxSessionFlags": {"description": "Session flags for each player", "unit": "irsdk_Flags"},
    "CarIdxSteer": {"description": "Steering wheel angle by car index", "unit": "rad"},
    "CarIdxTireCompound": {"description": "Cars current tire compound", "unit": ""},
    "CarIdxTrackSurface": {"description": "Track surface type by car index", "unit": "irsdk_TrkLoc"},
    "CarIdxTrackSurfaceMaterial": {"description": "Track surface material type by car index", "unit": "irsdk_TrkSurf"},
    "CarLeftRight": {"description": "Notify if car is to the left or right of driver", "unit": "irsdk_CarLeftRight"},
    "ChanAvgLatency": {"description": "Communications average latency", "unit": "s"},
    "ChanClockSkew": {"description": "Communications server clock skew", "unit": "s"},
    "ChanLatency": {"description": "Communications latency", "unit": "s"},
    "ChanPartnerQuality": {"description": "Partner communications quality", "unit": "%"},
    "ChanQuality": {"description": "Communications quality", "unit": "%"},
    "Clutch": {"description": "0=disengaged to 1=fully engaged", "unit": "%"},
    "ClutchRaw": {"description": "Raw clutch input 0=disengaged to 1=fully engaged", "unit": "%"},
    "CpuUsageBG": {"description": "Percent of available tim bg thread took with a 1 sec avg", "unit": "%"},
    "CpuUsageFG": {"description": "Percent of available tim fg thread took with a 1 sec avg", "unit": "%"},
    "DCDriversSoFar": {"description": "Number of team drivers who have run a stint", "unit": ""},
    "DCLapStatus": {"description": "Status of driver change lap requirements", "unit": ""},
    "dcPitSpeedLimiterToggle": {"description": "Track if pit speed limiter system is enabled", "unit": ""},
    "dcStarter": {"description": "In car trigger car starter", "unit": ""},
    "dcToggleWindshieldWipers": {"description": "In car turn wipers on or off", "unit": ""},
    "dcTriggerWindshieldWipers": {"description": "In car momentarily turn on wipers", "unit": ""},
    "DisplayUnits": {"description": "Default units for the user interface 0 = english 1 = metric", "unit": ""},
    "dpFastRepair": {"description": "Pitstop fast repair set", "unit": ""},
    "dpFuelAddKg": {"description": "Pitstop fuel add amount", "unit": "kg"},
    "dpFuelAutoFillActive": {"description": "Pitstop auto fill fuel next stop flag", "unit": ""},
    "dpFuelAutoFillEnabled": {"description": "Pitstop auto fill fuel system enabled", "unit": ""},
    "dpFuelFill": {"description": "Pitstop fuel fill flag", "unit": ""},
    "dpLFTireChange": {"description": "Pitstop lf tire change request", "unit": ""},
    "dpLFTireColdPress": {"description": "Pitstop lf tire cold pressure adjustment", "unit": "Pa"},
    "dpLRTireChange": {"description": "Pitstop lr tire change request", "unit": ""},
    "dpLRTireColdPress": {"description": "Pitstop lr tire cold pressure adjustment", "unit": "Pa"},
    "dpRFTireChange": {"description": "Pitstop rf tire change request", "unit": ""},
    "dpRFTireColdPress": {"description": "Pitstop rf cold tire pressure adjustment", "unit": "Pa"},
    "dpRRTireChange": {"description": "Pitstop rr tire change request", "unit": ""},
    "dpRRTireColdPress": {"description": "Pitstop rr cold tire pressure adjustment", "unit": "Pa"},
    "dpWindshieldTearoff": {"description": "Pitstop windshield tearoff", "unit": ""},
    "DriverMarker": {"description": "Driver activated flag", "unit": ""},
    "Engine0_RPM": {"description": "Engine0Engine rpm", "unit": "revs/min"},
    "EngineWarnings": {"description": "Bitfield for warning lights", "unit": "irsdk_EngineWarnings"},
    "EnterExitReset": {"description": "Indicate action the reset key will take 0 enter 1 exit 2 reset", "unit": ""},
    "FastRepairAvailable": {"description": "How many fast repairs left 255 is unlimited", "unit": ""},
    "FastRepairUsed": {"description": "How many fast repairs used so far", "unit": ""},
    "FogLevel": {"description": "Fog level at start/finish line", "unit": "%"},
    "FrameRate": {"description": "Average frames per second", "unit": "fps"},
    "FrontTireSetsAvailable": {"description": "How many front tire sets are remaining 255 is unlimited", "unit": ""},
    "FrontTireSetsUsed": {"description": "How many front tire sets used so far", "unit": ""},
    "FuelLevel": {"description": "Liters of fuel remaining", "unit": "l"},
    "FuelLevelPct": {"description": "Percent fuel remaining", "unit": "%"},
    "FuelPress": {"description": "Engine fuel pressure", "unit": "bar"},
    "FuelUsePerHour": {"description": "Engine fuel used instantaneous", "unit": "kg/h"},
    "Gear": {"description": "-1=reverse 0=neutral 1..n=current gear", "unit": ""},
    "GpuUsage": {"description": "Percent of available tim gpu took with a 1 sec avg", "unit": "%"},
    "HandbrakeRaw": {"description": "Raw handbrake input 0=handbrake released to 1=max force", "unit": "%"},
    "IsDiskLoggingActive": {"description": "0=disk based telemetry file not being written 1=being written", "unit": ""},
    "IsDiskLoggingEnabled": {"description": "0=disk based telemetry turned off 1=turned on", "unit": ""},
    "IsGarageVisible": {"description": "1=Garage screen is visible", "unit": ""},
    "IsInGarage": {"description": "1=Car in garage physics running", "unit": ""},
    "IsOnTrack": {"description": "1=Car on track physics running with player in car", "unit": ""},
    "IsOnTrackCar": {"description": "1=Car on track physics running", "unit": ""},
    "IsReplayPlaying": {"description": "0=replay not playing 1=replay playing", "unit": ""},
    "Lap": {"description": "Laps started count", "unit": ""},
    "LapBestLap": {"description": "Players best lap number", "unit": ""},
    "LapBestLapTime": {"description": "Players best lap time", "unit": "s"},
    "LapBestNLapLap": {"description": "Player last lap in best N average lap time", "unit": ""},
    "LapBestNLapTime": {"description": "Player best N average lap time", "unit": "s"},
    "LapCompleted": {"description": "Laps completed count", "unit": ""},
    "LapCurrentLapTime": {"description": "Estimate of players current lap time as shown in F3 box", "unit": "s"},
    "LapDeltaToBestLap": {"description": "Delta time for best lap", "unit": "s"},
    "LapDeltaToBestLap_DD": {"description": "Rate of change of delta time for best lap", "unit": "s/s"},
    "LapDeltaToBestLap_OK": {"description": "Delta time for best lap is valid", "unit": ""},
    "LapDeltaToOptimalLap": {"description": "Delta time for optimal lap", "unit": "s"},
    "LapDeltaToOptimalLap_DD": {"description": "Rate of change of delta time for optimal lap", "unit": "s/s"},
    "LapDeltaToOptimalLap_OK": {"description": "Delta time for optimal lap is valid", "unit": ""},
    "LapDeltaToSessionBestLap": {"description": "Delta time for session best lap", "unit": "s"},
    "LapDeltaToSessionBestLap_DD": {"description": "Rate of change of delta time for session best lap", "unit": "s/s"},
    "LapDeltaToSessionBestLap_OK": {"description": "Delta time for session best lap is valid", "unit": ""},
    "LapDeltaToSessionLastlLap": {"description": "Delta time for session last lap", "unit": "s"},
    "LapDeltaToSessionLastlLap_DD": {"description": "Rate of change of delta time for session last lap", "unit": "s/s"},
    "LapDeltaToSessionLastlLap_OK": {"description": "Delta time for session last lap is valid", "unit": ""},
    "LapDeltaToSessionOptimalLap": {"description": "Delta time for session optimal lap", "unit": "s"},
    "LapDeltaToSessionOptimalLap_DD": {"description": "Rate of change of delta time for session optimal lap", "unit": "s/s"},
    "LapDeltaToSessionOptimalLap_OK": {"description": "Delta time for session optimal lap is valid", "unit": ""},
    "LapDist": {"description": "Meters traveled from S/F this lap", "unit": "m"},
    "LapDistPct": {"description": "Percentage distance around lap", "unit": "%"},
    "LapLasNLapSeq": {"description": "Player num consecutive clean laps completed for N average", "unit": ""},
    "LapLastLapTime": {"description": "Players last lap time", "unit": "s"},
    "LapLastNLapTime": {"description": "Player last N average lap time", "unit": "s"},
    "LatAccel": {"description": "Lateral acceleration (including gravity)", "unit": "m/s^2"},
    "LatAccel_ST": {"description": "Lateral acceleration (including gravity) at 360 Hz", "unit": "m/s^2"},
    "LeftTireSetsAvailable": {"description": "How many left tire sets are remaining 255 is unlimited", "unit": ""},
    "LeftTireSetsUsed": {"description": "How many left tire sets used so far", "unit": ""},
    "LFbrakeLinePress": {"description": "LF brake line pressure", "unit": "bar"},
    "LFcoldPressure": {"description": "LF tire cold pressure as set in the garage", "unit": "kPa"},
    "LFshockDefl": {"description": "LF shock deflection", "unit": "m"},
    "LFshockDefl_ST": {"description": "LF shock deflection at 360 Hz", "unit": "m"},
    "LFshockVel": {"description": "LF shock velocity", "unit": "m/s"},
    "LFshockVel_ST": {"description": "LF shock velocity at 360 Hz", "unit": "m/s"},
    "LFtempCL": {"description": "LF tire left carcass temperature", "unit": "C"},
    "LFtempCM": {"description": "LF tire middle carcass temperature", "unit": "C"},
    "LFtempCR": {"description": "LF tire right carcass temperature", "unit": "C"},
    "LFTiresAvailable": {"description": "How many left front tires are remaining 255 is unlimited", "unit": ""},
    "LFTiresUsed": {"description": "How many left front tires used so far", "unit": ""},
    "LFwearL": {"description": "LF tire left percent tread remaining", "unit": "%"},
    "LFwearM": {"description": "LF tire middle percent tread remaining", "unit": "%"},
    "LFwearR": {"description": "LF tire right percent tread remaining", "unit": "%"},
    "LoadNumTextures": {"description": "True if the car_num texture will be loaded", "unit": ""},
    "LongAccel": {"description": "Longitudinal acceleration (including gravity)", "unit": "m/s^2"},
    "LongAccel_ST": {"description": "Longitudinal acceleration (including gravity) at 360 Hz", "unit": "m/s^2"},
    "LRbrakeLinePress": {"description": "LR brake line pressure", "unit": "bar"},
    "LRcoldPressure": {"description": "LR tire cold pressure as set in the garage", "unit": "kPa"},
    "LRshockDefl": {"description": "LR shock deflection", "unit": "m"},
    "LRshockDefl_ST": {"description": "LR shock deflection at 360 Hz", "unit": "m"},
    "LRshockVel": {"description": "LR shock velocity", "unit": "m/s"},
    "LRshockVel_ST": {"description": "LR shock velocity at 360 Hz", "unit": "m/s"},
    "LRtempCL": {"description": "LR tire left carcass temperature", "unit": "C"},
    "LRtempCM": {"description": "LR tire middle carcass temperature", "unit": "C"},
    "LRtempCR": {"description": "LR tire right carcass temperature", "unit": "C"},
    "LRTiresAvailable": {"description": "How many left rear tires are remaining 255 is unlimited", "unit": ""},
    "LRTiresUsed": {"description": "How many left rear tires used so far", "unit": ""},
    "LRwearL": {"description": "LR tire left percent tread remaining", "unit": "%"},
    "LRwearM": {"description": "LR tire middle percent tread remaining", "unit": "%"},
    "LRwearR": {"description": "LR tire right percent tread remaining", "unit": "%"},
    "ManifoldPress": {"description": "Engine manifold pressure", "unit": "bar"},
    "ManualBoost": {"description": "Hybrid manual boost state", "unit": ""},
    "ManualNoBoost": {"description": "Hybrid manual no boost state", "unit": ""},
    "MemPageFaultSec": {"description": "Memory page faults per second", "unit": ""},
    "MemSoftPageFaultSec": {"description": "Memory soft page faults per second", "unit": ""},
    "OilLevel": {"description": "Engine oil level", "unit": "l"},
    "OilPress": {"description": "Engine oil pressure", "unit": "bar"},
    "OilTemp": {"description": "Engine oil temperature", "unit": "C"},
    "OkToReloadTextures": {"description": "True if it is ok to reload car textures at this time", "unit": ""},
    "OnPitRoad": {"description": "Is the player car on pit road between the cones", "unit": ""},
    "P2P_Count": {"description": "Push2Pass count of usage (or remaining in Race) on your car", "unit": ""},
    "P2P_Status": {"description": "Push2Pass active or not on your car", "unit": ""},
    "PaceMode": {"description": "Are we pacing or not", "unit": "irsdk_PaceMode"},
    "Pitch": {"description": "Pitch orientation", "unit": "rad"},
    "PitchRate": {"description": "Pitch rate", "unit": "rad/s"},
    "PitchRate_ST": {"description": "Pitch rate at 360 Hz", "unit": "rad/s"},
    "PitOptRepairLeft": {"description": "Time left for optional repairs if repairs are active", "unit": "s"},
    "PitRepairLeft": {"description": "Time left for mandatory pit repairs if repairs are active", "unit": "s"},
    "PitsOpen": {"description": "True if pit stop is allowed for the current player", "unit": ""},
    "PitstopActive": {"description": "Is the player getting pit stop service", "unit": ""},
    "PitSvFlags": {"description": "Bitfield of pit service checkboxes", "unit": "irsdk_PitSvFlags"},
    "PitSvFuel": {"description": "Pit service fuel add amount", "unit": "l or kWh"},
    "PitSvLFP": {"description": "Pit service left front tire pressure", "unit": "kPa"},
    "PitSvLRP": {"description": "Pit service left rear tire pressure", "unit": "kPa"},
    "PitSvRFP": {"description": "Pit service right front tire pressure", "unit": "kPa"},
    "PitSvRRP": {"description": "Pit service right rear tire pressure", "unit": "kPa"},
    "PitSvTireCompound": {"description": "Pit service pending tire compound", "unit": ""},
    "PlayerCarClass": {"description": "Player car class id", "unit": ""},
    "PlayerCarClassPosition": {"description": "Players class position in race", "unit": ""},
    "PlayerCarDriverIncidentCount": {"description": "Teams current drivers incident count for this session", "unit": ""},
    "PlayerCarDryTireSetLimit": {"description": "Players dry tire set limit", "unit": ""},
    "PlayerCarIdx": {"description": "Players carIdx", "unit": ""},
    "PlayerCarInPitStall": {"description": "Players car is properly in their pitstall", "unit": ""},
    "PlayerCarMyIncidentCount": {"description": "Players own incident count for this session", "unit": ""},
    "PlayerCarPitSvStatus": {"description": "Players car pit service status bits", "unit": "irsdk_PitSvStatus"},
    "PlayerCarPosition": {"description": "Players position in race", "unit": ""},
    "PlayerCarPowerAdjust": {"description": "Players power adjust", "unit": "%"},
    "PlayerCarSLBlinkRPM": {"description": "Shift light blink rpm", "unit": "revs/min"},
    "PlayerCarSLFirstRPM": {"description": "Shift light first light rpm", "unit": "revs/min"},
    "PlayerCarSLLastRPM": {"description": "Shift light last light rpm", "unit": "revs/min"},
    "PlayerCarSLShiftRPM": {"description": "Shift light shift rpm", "unit": "revs/min"},
    "PlayerCarTeamIncidentCount": {"description": "Players team incident count for this session", "unit": ""},
    "PlayerCarTowTime": {"description": "Players car is being towed if time is greater than zero", "unit": "s"},
    "PlayerCarWeightPenalty": {"description": "Players weight penalty", "unit": "kg"},
    "PlayerFastRepairsUsed": {"description": "Players car number of fast repairs used", "unit": ""},
    "PlayerTireCompound": {"description": "Players car current tire compound", "unit": ""},
    "PlayerTrackSurface": {"description": "Players car track surface type", "unit": "irsdk_TrkLoc"},
    "PlayerTrackSurfaceMaterial": {"description": "Players car track surface material type", "unit": "irsdk_TrkSurf"},
    "Precipitation": {"description": "Precipitation at start/finish line", "unit": "%"},
    "PushToPass": {"description": "Push to pass button state", "unit": ""},
    "PushToTalk": {"description": "Push to talk button state", "unit": ""},
    "RaceLaps": {"description": "Laps completed in race", "unit": ""},
    "RadioTransmitCarIdx": {"description": "The car index of the current person speaking on the radio", "unit": ""},
    "RadioTransmitFrequencyIdx": {"description": "The frequency index of the current person speaking on the radio", "unit": ""},
    "RadioTransmitRadioIdx": {"description": "The radio index of the current person speaking on the radio", "unit": ""},
    "RearTireSetsAvailable": {"description": "How many rear tire sets are remaining 255 is unlimited", "unit": ""},
    "RearTireSetsUsed": {"description": "How many rear tire sets used so far", "unit": ""},
    "RelativeHumidity": {"description": "Relative Humidity at start/finish line", "unit": "%"},
    "ReplayFrameNum": {"description": "Integer replay frame number (60 per second)", "unit": ""},
    "ReplayFrameNumEnd": {"description": "Integer replay frame number from end of tape", "unit": ""},
    "ReplayPlaySlowMotion": {"description": "0=not slow motion 1=replay is in slow motion", "unit": ""},
    "ReplayPlaySpeed": {"description": "Replay playback speed", "unit": ""},
    "ReplaySessionNum": {"description": "Replay session number", "unit": ""},
    "ReplaySessionTime": {"description": "Seconds since replay session start", "unit": "s"},
    "RFbrakeLinePress": {"description": "RF brake line pressure", "unit": "bar"},
    "RFcoldPressure": {"description": "RF tire cold pressure as set in the garage", "unit": "kPa"},
    "RFshockDefl": {"description": "RF shock deflection", "unit": "m"},
    "RFshockDefl_ST": {"description": "RF shock deflection at 360 Hz", "unit": "m"},
    "RFshockVel": {"description": "RF shock velocity", "unit": "m/s"},
    "RFshockVel_ST": {"description": "RF shock velocity at 360 Hz", "unit": "m/s"},
    "RFtempCL": {"description": "RF tire left carcass temperature", "unit": "C"},
    "RFtempCM": {"description": "RF tire middle carcass temperature", "unit": "C"},
    "RFtempCR": {"description": "RF tire right carcass temperature", "unit": "C"},
    "RFTiresAvailable": {"description": "How many right front tires are remaining 255 is unlimited", "unit": ""},
    "RFTiresUsed": {"description": "How many right front tires used so far", "unit": ""},
    "RFwearL": {"description": "RF tire left percent tread remaining", "unit": "%"},
    "RFwearM": {"description": "RF tire middle percent tread remaining", "unit": "%"},
    "RFwearR": {"description": "RF tire right percent tread remaining", "unit": "%"},
    "RightTireSetsAvailable": {"description": "How many right tire sets are remaining 255 is unlimited", "unit": ""},
    "RightTireSetsUsed": {"description": "How many right tire sets used so far", "unit": ""},
    "Roll": {"description": "Roll orientation", "unit": "rad"},
    "RollRate": {"description": "Roll rate", "unit": "rad/s"},
    "RollRate_ST": {"description": "Roll rate at 360 Hz", "unit": "rad/s"},
    "RPM": {"description": "Engine rpm", "unit": "revs/min"},
    "RRbrakeLinePress": {"description": "RR brake line pressure", "unit": "bar"},
    "RRcoldPressure": {"description": "RR tire cold pressure as set in the garage", "unit": "kPa"},
    "RRshockDefl": {"description": "RR shock deflection", "unit": "m"},
    "RRshockDefl_ST": {"description": "RR shock deflection at 360 Hz", "unit": "m"},
    "RRshockVel": {"description": "RR shock velocity", "unit": "m/s"},
    "RRshockVel_ST": {"description": "RR shock velocity at 360 Hz", "unit": "m/s"},
    "RRtempCL": {"description": "RR tire left carcass temperature", "unit": "C"},
    "RRtempCM": {"description": "RR tire middle carcass temperature", "unit": "C"},
    "RRtempCR": {"description": "RR tire right carcass temperature", "unit": "C"},
    "RRTiresAvailable": {"description": "How many right rear tires are remaining 255 is unlimited", "unit": ""},
    "RRTiresUsed": {"description": "How many right rear tires used so far", "unit": ""},
    "RRwearL": {"description": "RR tire left percent tread remaining", "unit": "%"},
    "RRwearM": {"description": "RR tire middle percent tread remaining", "unit": "%"},
    "RRwearR": {"description": "RR tire right percent tread remaining", "unit": "%"},
    "SessionFlags": {"description": "Session flags", "unit": "irsdk_Flags"},
    "SessionJokerLapsRemain": {"description": "Joker laps remaining to be taken", "unit": ""},
    "SessionLapsRemain": {"description": "Old laps left till session ends use SessionLapsRemainEx", "unit": ""},
    "SessionLapsRemainEx": {"description": "New improved laps left till session ends", "unit": ""},
    "SessionLapsTotal": {"description": "Total number of laps in session", "unit": ""},
    "SessionNum": {"description": "Session number", "unit": ""},
    "SessionOnJokerLap": {"description": "Player is currently completing a joker lap", "unit": ""},
    "SessionState": {"description": "Session state", "unit": "irsdk_SessionState"},
    "SessionTick": {"description": "Current update number", "unit": ""},
    "SessionTime": {"description": "Seconds since session start", "unit": "s"},
    "SessionTimeOfDay": {"description": "Time of day in seconds", "unit": "s"},
    "SessionTimeRemain": {"description": "Seconds left till session ends", "unit": "s"},
    "SessionTimeTotal": {"description": "Total number of seconds in session", "unit": "s"},
    "SessionUniqueID": {"description": "Session ID", "unit": ""},
    "ShiftGrindRPM": {"description": "RPM of shifter grinding noise", "unit": "RPM"},
    "ShiftIndicatorPct": {"description": "DEPRECATED use DriverCarSLBlinkRPM instead", "unit": "%"},
    "ShiftPowerPct": {"description": "Friction torque applied to gears when shifting or grinding", "unit": "%"},
    "Skies": {"description": "Skies (0=clear/1=p cloudy/2=m cloudy/3=overcast)", "unit": ""},
    "SolarAltitude": {"description": "Sun angle above horizon in radians", "unit": "rad"},
    "SolarAzimuth": {"description": "Sun angle clockwise from north in radians", "unit": "rad"},
    "Speed": {"description": "GPS vehicle speed", "unit": "m/s"},
    "SteeringFFBEnabled": {"description": "Force feedback is enabled", "unit": ""},
    "SteeringWheelAngle": {"description": "Steering wheel angle", "unit": "rad"},
    "SteeringWheelAngleMax": {"description": "Steering wheel max angle", "unit": "rad"},
    "SteeringWheelLimiter": {"description": "Force feedback limiter strength limits impacts and oscillation", "unit": "%"},
    "SteeringWheelMaxForceNm": {"description": "Value of strength or max force slider in Nm for FFB", "unit": "N*m"},
    "SteeringWheelPctDamper": {"description": "Force feedback % max damping", "unit": "%"},
    "SteeringWheelPctIntensity": {"description": "Force feedback % max intensity", "unit": "%"},
    "SteeringWheelPctSmoothing": {"description": "Force feedback % max smoothing", "unit": "%"},
    "SteeringWheelPctTorque": {"description": "Force feedback % max torque on steering shaft unsigned", "unit": "%"},
    "SteeringWheelPctTorqueSign": {"description": "Force feedback % max torque on steering shaft signed", "unit": "%"},
    "SteeringWheelPctTorqueSignStops": {"description": "Force feedback % max torque on steering shaft signed stops", "unit": "%"},
    "SteeringWheelPeakForceNm": {"description": "Peak torque mapping to direct input units for FFB", "unit": "N*m"},
    "SteeringWheelTorque": {"description": "Output torque on steering shaft", "unit": "N*m"},
    "SteeringWheelTorque_ST": {"description": "Output torque on steering shaft at 360 Hz", "unit": "N*m"},
    "SteeringWheelUseLinear": {"description": "True if steering wheel force is using linear mode", "unit": ""},
    "Throttle": {"description": "0=off throttle to 1=full throttle", "unit": "%"},
    "ThrottleRaw": {"description": "Raw throttle input 0=off throttle to 1=full throttle", "unit": "%"},
    "TireLF_RumblePitch": {"description": "Players LF Tire Sound rumblestrip pitch", "unit": "Hz"},
    "TireLR_RumblePitch": {"description": "Players LR Tire Sound rumblestrip pitch", "unit": "Hz"},
    "TireRF_RumblePitch": {"description": "Players RF Tire Sound rumblestrip pitch", "unit": "Hz"},
    "TireRR_RumblePitch": {"description": "Players RR Tire Sound rumblestrip pitch", "unit": "Hz"},
    "TireSetsAvailable": {"description": "How many tire sets are remaining 255 is unlimited", "unit": ""},
    "TireSetsUsed": {"description": "How many tire sets used so far", "unit": ""},
    "TrackTemp": {"description": "Deprecated set to TrackTempCrew", "unit": "C"},
    "TrackTempCrew": {"description": "Temperature of track measured by crew around track", "unit": "C"},
    "TrackWetness": {"description": "How wet is the average track surface", "unit": "irsdk_TrackWetness"},
    "VelocityX": {"description": "X velocity", "unit": "m/s"},
    "VelocityX_ST": {"description": "X velocity", "unit": "m/s at 360 Hz"},
    "VelocityY": {"description": "Y velocity", "unit": "m/s"},
    "VelocityY_ST": {"description": "Y velocity", "unit": "m/s at 360 Hz"},
    "VelocityZ": {"description": "Z velocity", "unit": "m/s"},
    "VelocityZ_ST": {"description": "Z velocity", "unit": "m/s at 360 Hz"},
    "VertAccel": {"description": "Vertical acceleration (including gravity)", "unit": "m/s^2"},
    "VertAccel_ST": {"description": "Vertical acceleration (including gravity) at 360 Hz", "unit": "m/s^2"},
    "VidCapActive": {"description": "True if video currently being captured", "unit": ""},
    "VidCapEnabled": {"description": "True if video capture system is enabled", "unit": ""},
    "Voltage": {"description": "Engine voltage", "unit": "V"},
    "WaterLevel": {"description": "Engine coolant level", "unit": "l"},
    "WaterTemp": {"description": "Engine coolant temp", "unit": "C"},
    "WeatherDeclaredWet": {"description": "The steward says rain tires can be used", "unit": ""},
    "WindDir": {"description": "Wind direction at start/finish line", "unit": "rad"},
    "WindVel": {"description": "Wind velocity at start/finish line", "unit": "m/s"},
    "Yaw": {"description": "Yaw orientation", "unit": "rad"},
    "YawNorth": {"description": "Yaw orientation relative to north", "unit": "rad"},
    "YawRate": {"description": "Yaw rate", "unit": "rad/s"},
    "YawRate_ST": {"description": "Yaw rate at 360 Hz", "unit": "rad/s"}
}

# Example of how to access data:
# print(iracing_telemetry_data["FuelLevel"])
# print(iracing_telemetry_data["Speed"]["unit"])
